name: Environmental Variables
on: workflow_dispatch
env:
  name: Raghav
jobs:
 TestJob:
   runs-on: ubuntu-latest
   steps:
   - name: Using Environmental Variables
     run: echo ${{ env.name }} 
   - name: Using Normal Variables
     run: echo ${{ vars.x }}
